"""seed_scroll_of_onymyoji_server

Revision ID: 4013650772f7
Revises: 3036bbe42472
Create Date: 2024-01-06 05:43:08.735411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4013650772f7'
down_revision: Union[str, None] = '3036bbe42472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('''
    	INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S1-Taman sakura', 's1-taman-sakura', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S2-Akademi Mitama', 's2-akademi-mitama', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S3-Gunung roh', 's3-gunung-roh', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S4-Ketiadaan', 's4-ketiadaan', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S5-Kosong', 's5-kosong', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S6-Stargate', 's6-stargate', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S7-Realm Takdir', 's7-realm-takdir', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S8-Reruntuhan', 's8-reruntuhan', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S9-Kuil Cahaya', 's9-kuil-cahaya', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S10-Pavilion langit', 's10-pavilion-langit', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S11-Taman impian', 's11-taman-impian', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S12-Hutan diam', 's12-hutan-diam', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S13-Jalur Langit', 's13-jalur-langit', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S14-Pencarian Buluh', 's14-pencarian-buluh', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S15-Misteri Elf', 's15-misteri-elf', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S16-Hutan roh iblis', 's16-hutan-roh-iblis', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S17-Laut dalam', 's17-laut-dalam', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S18-Kuil Beruang', 's18-kuil-beruang', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S19-Domain kegelapan', 's19-domain-kegelapan', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S20-Distorsi', 's20-distorsi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S21-Kenshi', 's21-kenshi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S22-Uzume', 's22-uzume', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S23-Fujin', 's23-fujin', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S24-Inari', 's24-inari', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S25-Shikoku', 's25-shikoku', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S26-Okami', 's26-okami', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S27-Nagi', 's27-nagi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S28-Kojiki', 's28-kojiki', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S29-Raijin', 's29-raijin', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S30-Suijin', 's30-suijin', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S31-Susanoo', 's31-susanoo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S32-Orochi', 's32-orochi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S33-Tenjin', 's33-tenjin', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S34-Otohime', 's34-otohime', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S35-Ame', 's35-ame', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S36-Kaguya', 's36-kaguya', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S37-Hana', 's37-hana', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S38-Kojin', 's38-kojin', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S39-Mikoto', 's39-mikoto', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S40-Jizo', 's40-jizo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S41-Konoha', 's41-konoha', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S42-Aizen', 's42-aizen', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S43-Kannon', 's43-kannon', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S44-Ebisu', 's44-ebisu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S45-Danau berkabut', 's45-danau-berkabut', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S46-Gunung monster', 's46-gunung-monster', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S47-Kota Bulan', 's47-kota-bulan', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S48-Hutan Ajaib', 's48-hutan-ajaib', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S49-Balai Bumi', 's49-balai-bumi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S50-Oiwa', 's50-oiwa', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S51-Sazae Oni', 's51-sazae-oni', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S52-Yama Uba', 's52-yama-uba', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S53-Hannya', 's53-hannya', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S54-Namanari', 's54-namanari', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S55-Ikiryo', 's55-ikiryo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S56-Chunari', 's56-chunari', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S57-Honnari', 's57-honnari', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S58-Ubume', 's58-ubume', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S59-Nure Onna', 's59-nure-onna', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S60-Nukekubi', 's60-nukekubi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S61-Rokurkubi', 's61-rokurkubi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S62-Ubagabi', 's62-ubagabi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S63-Hone Onna', 's63-hone-onna', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S64-Akashita', 's64-akashita', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S65-Kiyohime', 's65-kiyohime', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S66-Obake', 's66-obake', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S67-Kamaitaichi', 's67-kamaitaichi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S68-Kekkai', 's68-kekkai', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S69-Isonade', 's69-isonade', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S70-Masakatsu', 's70-masakatsu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S71-Yasumori', 's71-yasumori', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S72-Mototsuna', 's72-mototsuna', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S73-Kagemori', 's73-kagemori', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S74-Terukage', 's74-terukage', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S75-Mitsuhide', 's75-mitsuhide', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S76-Nobutomo', 's76-nobutomo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S77-Yoshihisa', 's77-yoshihisa', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S78-Morinari', 's78-morinari', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S79-Shigetsuna', 's79-shigetsuna', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S80-Yurei', 's80-yurei', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S81-Aokage', 's81-aokage', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S82-Muratsugu', 's82-muratsugu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S83-Arima', 's83-arima', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S84-Hisamasa', 's84-hisamasa', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S85-Nagaharu', 's85-nagaharu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S86-Morichika', 's86-morichika', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S87-Shigezane', 's87-shigezane', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S88-Masamune', 's88-masamune', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S89-Toshikatsu', 's89-toshikatsu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S90-Fusahide', 's90-fusahide', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S91-Ujisato', 's91-ujisato', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S92-Naomasa', 's92-naomasa', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S93-Tsunenaga', 's93-tsunenaga', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S94-Hattori', 's94-hattori', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S95-Hideharu', 's95-hideharu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S96-Kennyo', 's96-kennyo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S97-Masatoshi', 's97-masatoshi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S98-Tsuneoki', 's98-tsuneoki', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S99-Isshiki', 's99-isshiki', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S100-Imagawa', 's100-imagawa', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S101-Hiroie', 's101-hiroie', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S102-Yukinaga', 's102-yukinaga', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S103-Hisamichi', 's103-hisamichi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S104-Matsudaira', 's104-matsudaira', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S105-Hatobo', 's105-hatobo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S106-Nageki', 's106-nageki', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S107-Kappa', 's107-kappa', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S108-Ryuo', 's108-ryuo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S109-Nozuchi', 's109-nozuchi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S110-Yosei', 's110-yosei', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S111-Ushirogami', 's111-ushirogami', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S112-Tsurube', 's112-tsurube', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S113-Tsukuyomi', 's113-tsukuyomi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S114-Momonji', 's114-momonji', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S115-Suzaku', 's115-suzaku', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S116-Seiryuu', 's116-seiryuu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S117-Byakko', 's117-byakko', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S118-Genbu', 's118-genbu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S119-Shiryo', 's119-shiryo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S120-Kahaku', 's120-kahaku', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S121-Rojinbi', 's121-rojinbi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S122-Onryo', 's122-onryo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S123-Kasha', 's123-kasha', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S124-Tenko', 's124-tenko', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S125-Nue', 's125-nue', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S126-Yuki-Onna', 's126-yuki-onna', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S127-Mononoke', 's127-mononoke', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S128-Okiku', 's128-okiku', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S129-Kodama', 's129-kodama', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S130-Issie', 's130-issie', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S131-Hakano', 's131-hakano', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S132-Gyuki', 's132-gyuki', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S133-Funayurei', 's133-funayurei', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S134-Dodomeki', 's134-dodomeki', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S135-Kosagi', 's135-kosagi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S136-Kirin', 's136-kirin', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S137-Amesu', 's137-amesu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S138-Akubozu', 's138-akubozu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S139-Yuuki', 's139-yuuki', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S140-Supia', 's140-supia', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S141-Onisuzume', 's141-onisuzume', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S142-Nyoromo', 's142-nyoromo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S143-Kishi', 's143-kishi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S144-Utsudon', 's144-utsudon', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S145-Nashi', 's145-nashi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S146-Myuu', 's146-myuu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S147-Kabuto', 's147-kabuto', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S148-Iibui', 's148-iibui', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S149-Azumao', 's149-azumao', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S150-Rakki', 's150-rakki', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S151-Ebiwara', 's151-ebiwara', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S152-Tama', 's152-tama', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S153-Jugon', 's153-jugon', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S154-Koiru', 's154-koiru', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S155-Gyaropu', 's155-gyaropu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S156-Uindie', 's156-uindie', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S157-Soma', 's157-soma', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S158-Rokon', 's158-rokon', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S159-Korata', 's159-korata', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S160-Catapi', 's160-catapi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S161-Suripu', 's161-suripu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S162-Hitokage', 's162-hitokage', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S163-Kameru', 's163-kameru', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S164-Toranseru', 's164-toranseru', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S165-Onidoriru', 's165-onidoriru', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S166-Kokun', 's166-kokun', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S167-Pukuri', 's167-pukuri', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S168-Kyatapi', 's168-kyatapi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S169-Gadi', 's169-gadi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S170-Nyomoro', 's170-nyomoro', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S171-Saihon', 's171-saihon', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S172-Genga', 's172-genga', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S173-Iwaku', 's173-iwaku', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S174-Rujura', 's174-rujura', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S175-Nyasu', 's175-nyasu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S176-Hakuryu', 's176-hakuryu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S177-Furiza', 's177-furiza', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S178-Myutsu', 's178-myutsu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S179-Odairu', 's179-odairu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S180-Otachi', 's180-otachi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S181-Himanatsu', 's181-himanatsu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S182-Kimawari', 's182-kimawari', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S183-Guraiga', 's183-guraiga', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S184-Nyura', 's184-nyura', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S185-Daikon', 's185-daikon', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S186-Kiruria', 's186-kiruria', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S187-Sanaito', 's187-sanaito', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S188-Kingu', 's188-kingu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S189-Tsuchinin', 's189-tsuchinin', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S190-Yajiron', 's190-yajiron', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S191-Jiransu', 's191-jiransu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S192-Todogura', 's192-todogura', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S193-Hayashi', 's193-hayashi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S194-Ratiosu', 's194-ratiosu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S195-Hikozaru', 's195-hikozaru', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S196-Nyaruma', 's196-nyaruma', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S197-Tamanta', 's197-tamanta', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S198-Hyakki', 's198-hyakki', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S199-Ishimai', 's199-ishimai', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S200-Zoroa', 's200-zoroa', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S201-Rigure', 's201-rigure', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S202-Obemu', 's202-obemu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S203-Shishiko', 's203-shishiko', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S204-Hitotsuki', 's204-hitotsuki', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S205-Maika', 's205-maika', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S206-Kuzumo', 's206-kuzumo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S207-GIN', 's207-gin', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S208-ARNIUS', 's208-arnius', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S209-DAICHI', 's209-daichi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S210-EIJI', 's210-eiji', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S211-HIDEYOSHI', 's211-hideyoshi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S212-HARU', 's212-haru', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S213-HINOTO', 's213-hinoto', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S214-HADJI', 's214-hadji', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S215-HIRO', 's215-hiro', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S216-HIKARU', 's216-hikaru', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S217-ISAMU', 's217-isamu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S218-ICHIRO', 's218-ichiro', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S219-KADO', 's219-kado', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S220-KAINDRA', 's220-kaindra', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S221-KENSHI', 's221-kenshi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S222-KENICHI', 's222-kenichi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S223-KO', 's223-ko', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S224-KAZUO', 's224-kazuo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S225-MAMORU', 's225-mamoru', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S226-MASKUR', 's226-maskur', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S227-MASHASHI', 's227-mashashi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S228-MASUMI', 's228-masumi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S229-MASO', 's229-maso', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S230-KOBAYASHI', 's230-kobayashi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S231-MIKIO', 's231-mikio', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S232-MASAYUKI', 's232-masayuki', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S233-MAKOTO', 's233-makoto', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S234-MORIO', 's234-morio', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S235-NANDITO', 's235-nandito', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S236-NAOKI', 's236-naoki', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S237-NAOTO', 's237-naoto', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S238-ICHIMARU', 's238-ichimaru', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S239-KAWAGUCHI', 's239-kawaguchi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S240-NOBU', 's240-nobu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S241-NIKY', 's241-niky', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S242-OKI', 's242-oki', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S243-NORI', 's243-nori', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S244-NOBORU', 's244-noboru', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S245-RAIDEN', 's245-raiden', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S246-REN', 's246-ren', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S247-GYO', 's247-gyo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S248-NEN', 's248-nen', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S249-TEN', 's249-ten', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S250-MASHASHI', 's250-mashashi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S251-KENSHI', 's251-kenshi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S252-RYOICHI', 's252-ryoichi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S253-REIYU', 's253-reiyu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S254-RINGO', 's254-ringo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S255-ROKA', 's255-roka', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S256-RIYO', 's256-riyo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S257-RYOTA', 's257-ryota', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S258-RYU', 's258-ryu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S259-RYUZAKI', 's259-ryuzaki', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S260-SAYKOJI', 's260-saykoji', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S261-SUZANO', 's261-suzano', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S262-SANO', 's262-sano', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S263-SABURO', 's263-saburo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S264-SEIKO', 's264-seiko', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S265-SEIYA', 's265-seiya', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S266-SHIN', 's266-shin', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S267-SHIRO', 's267-shiro', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S268-SHINJI', 's268-shinji', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S269-SINA', 's269-sina', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S270-SORA', 's270-sora', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S271-SATORU', 's271-satoru', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S272-SHIMA', 's272-shima', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S273-SHOUHEI', 's273-shouhei', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S274-SHUJI', 's274-shuji', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S275-SHINICHI', 's275-shinichi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S276-SUNO', 's276-suno', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S277-TAMA', 's277-tama', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S278-TARO', 's278-taro', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S279-TOMI', 's279-tomi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S280-TAKAO', 's280-takao', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S281-TAKASHI', 's281-takashi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S282-TAKEDA', 's282-takeda', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S283-TSUTOMU', 's283-tsutomu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S284-TOSHIO', 's284-toshio', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S285-TOSHIRO', 's285-toshiro', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S286-YUKI', 's286-yuki', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S287-YOSHIMITSU', 's287-yoshimitsu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S288-YASUO', 's288-yasuo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S289-ZEN', 's289-zen', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S290-NEIJI', 's290-neiji', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S291-ICHIGO', 's291-ichigo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S292-KUROSAWA', 's292-kurosawa', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S293-YUUTO', 's293-yuuto', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S294-KINDAICHI', 's294-kindaichi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S295-YASHUHIRO', 's295-yashuhiro', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S296-YASUO', 's296-yasuo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S297-AYA', 's297-aya', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S298-AYUMI', 's298-ayumi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S299-CHEIKO', 's299-cheiko', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S300-AYAKO', 's300-ayako', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S301-Cybele', 's301-cybele', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S302-Skadi', 's302-skadi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S303-Ashtoreth', 's303-ashtoreth', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S304-Asherah', 's304-asherah', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S305-Lamia', 's305-lamia', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S306-Hariti', 's306-hariti', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S307-Dakini', 's307-dakini', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S308-Kali', 's308-kali', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S309-Goemon', 's309-goemon', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S310-Eligor', 's310-eligor', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S311-Thoth', 's311-thoth', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S312-Barong', 's312-barong', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S313-Rangda', 's313-rangda', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S314-Strix', 's314-strix', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S315-Tengu', 's315-tengu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S316-Gamayun', 's316-gamayun', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S317-Hippogriff', 's317-hippogriff', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S318-Salawa', 's318-salawa', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S319-Barghest', 's319-barghest', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S320-Sigbin', 's320-sigbin', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S321-Muninn', 's321-muninn', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S322-Midgard', 's322-midgard', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S323-Fossegrim', 's323-fossegrim', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S324-Ratatoskr', 's324-ratatoskr', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S325-Yggdrasil', 's325-yggdrasil', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S326-Jotunheimen', 's326-jotunheimen', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S327-Borr', 's327-borr', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S328-Idun', 's328-idun', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S329-Bragi', 's329-bragi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S330-Forseti', 's330-forseti', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S331-Gjallarhorn', 's331-gjallarhorn', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S332-Vali', 's332-vali', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S333-Nerthus', 's333-nerthus', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S334-Ullr', 's334-ullr', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S335-Sif', 's335-sif', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S336-Glitnir', 's336-glitnir', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S337-Hermod', 's337-hermod', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S338-Gefjun', 's338-gefjun', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S339-Fjorgynn', 's339-fjorgynn', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S340-Sol', 's340-sol', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S341-Gatotkaca', 's341-gatotkaca', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S342-Yudhistira', 's342-yudhistira', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S343-Bima', 's343-bima', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S344-Arjuna', 's344-arjuna', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S345-Nakula', 's345-nakula', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S346-Sadewa', 's346-sadewa', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S347-Siliwangi', 's347-siliwangi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S348-AnglingDharma', 's348-anglingdharma', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S349-Purbasari', 's349-purbasari', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S350-JakaTingkir', 's350-jakatingkir', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S351-Abumiguchi', 's351-abumiguchi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S352-Chochinbi', 's352-chochinbi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S353-Hakutaku', 's353-hakutaku', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S354-Bakeneko', 's354-bakeneko', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S355-Jubokko', 's355-jubokko', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S356-Akabeko', 's356-akabeko', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S357-Hyosube', 's357-hyosube', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S358-Ikuchi', 's358-ikuchi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S359-Basan', 's359-basan', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S360-Akashita', 's360-akashita', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S361-Daitengu', 's361-daitengu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S362-Kameosa', 's362-kameosa', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S363-Momonji', 's363-momonji', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S364-Amamehagi', 's364-amamehagi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S365-Hinode', 's365-hinode', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S366-Issie', 's366-issie', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S367-Kawauso', 's367-kawauso', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S368-Hotoke', 's368-hotoke', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S369-Amanozako', 's369-amanozako', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S370-Kanedama', 's370-kanedama', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S371-Harionago', 's371-harionago', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S372-Keneo', 's372-keneo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S373-Bashonosei', 's373-bashonosei', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S374-Jatai', 's374-jatai', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S375-Aosaginohi', 's375-aosaginohi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S376-Hannya', 's376-hannya', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S377-Goryo', 's377-goryo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S378-Karura', 's378-karura', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S379-Funayurei', 's379-funayurei', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S380-Itsumade', 's380-itsumade', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S381-Mikaribaba', 's381-mikaribaba', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S382-Dodomeki', 's382-dodomeki', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S383-Kangiten', 's383-kangiten', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S384-Hitodama', 's384-hitodama', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S385-Jibakurei', 's385-jibakurei', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S386-Mizuchi', 's386-mizuchi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S387-Hososhi', 's387-hososhi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S388-Ikiryo', 's388-ikiryo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S389-Mujina', 's389-mujina', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S390-Isonade', 's390-isonade', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S391-Furaribi', 's391-furaribi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S392-Kasha', 's392-kasha', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S393-Janjanbi', 's393-janjanbi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S394-Enenra', 's394-enenra', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S395-Hashihime', 's395-hashihime', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S396-Gashadokuro', 's396-gashadokuro', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S397-Kamikiri', 's397-kamikiri', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S398-Fujin', 's398-fujin', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S399-Gozu', 's399-gozu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S400-Mezu', 's400-mezu', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S401-Sirius', 's401-sirius', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S402-Polaris', 's402-polaris', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S403-Claia', 's403-claia', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S404-Karya', 's404-karya', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S405-Ekho', 's405-ekho', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S406-Balanis', 's406-balanis', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S407-Midas', 's407-midas', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S408-MidasLeda', 's408-midasleda', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S409-Ixion', 's409-ixion', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S410-Iamus', 's410-iamus', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S411-Evadne', 's411-evadne', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S412-Geryon', 's412-geryon', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S413-Eryx', 's413-eryx', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S414-Apus', 's414-apus', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S415-Antlia', 's415-antlia', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S416-Reticulum', 's416-reticulum', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S417-Octans', 's417-octans', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S418-Microscopium', 's418-microscopium', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S419-Telescopium', 's419-telescopium', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S420-Circinus', 's420-circinus', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S421-Norma', 's421-norma', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S422-Bootes', 's422-bootes', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S423-Canes', 's423-canes', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S424-Draco', 's424-draco', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S425-Ursa Minor', 's425-ursa-minor', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S426-Ursa Major', 's426-ursa-major', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S427-Monoceros', 's427-monoceros', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S428-Lepus', 's428-lepus', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S429-Canis Major', 's429-canis-major', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S430-Orion', 's430-orion', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S431-Ara', 's431-ara', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S432-Lupus', 's432-lupus', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S433-Centaurus', 's433-centaurus', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S434-Serpens', 's434-serpens', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S435-Ophiuchus', 's435-ophiuchus', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S436-Corvus', 's436-corvus', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S437-Crater', 's437-crater', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S438-Hydra', 's438-hydra', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S439-Cygnus', 's439-cygnus', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S440-Lyra', 's440-lyra', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S441-Aquila', 's441-aquila', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S442-Sagitta', 's442-sagitta', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S443-Hercules', 's443-hercules', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S444-Auriga', 's444-auriga', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S445-Pegasus', 's445-pegasus', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S446-Cepheus', 's446-cepheus', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S447-Cetus', 's447-cetus', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S448-Cassiopeia', 's448-cassiopeia', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S449-Perseus', 's449-perseus', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S450-Andromeda', 's450-andromeda', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S451-Sagittarius', 's451-sagittarius', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S452-Scorpio', 's452-scorpio', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S453-Libra', 's453-libra', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S454-Virgo', 's454-virgo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S455-Leo', 's455-leo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S456-Cancer', 's456-cancer', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S457-Gemini', 's457-gemini', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S458-Taurus', 's458-taurus', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S459-Aries', 's459-aries', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S460-Pisces', 's460-pisces', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S461-Aquarius', 's461-aquarius', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S462-Summer', 's462-summer', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S463-Lakshmi', 's463-lakshmi', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S464-Norn', 's464-norn', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S465-Europa', 's465-europa', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S466-Chandra', 's466-chandra', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S467-Agni', 's467-agni', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S468-Narada', 's468-narada', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S469-Uluka', 's469-uluka', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S470-Byasa', 's470-byasa', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S471-Damayanti', 's471-damayanti', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S472-Taksaka', 's472-taksaka', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S473-Sweta', 's473-sweta', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S474-Nala', 's474-nala', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S475-Madri', 's475-madri', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S476-Bajradata', 's476-bajradata', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S477-Surasena', 's477-surasena', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S478-Hyperion', 's478-hyperion', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S479-Parumleo', 's479-parumleo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S480-Wezen', 's480-wezen', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S481-Columba', 's481-columba', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S482-Spica', 's482-spica', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S483-Pavo', 's483-pavo', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S484-Vela', 's484-vela', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S485-Giausar', 's485-giausar', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S486-Tucana', 's486-tucana', '0');
		INSERT INTO "MTServer"("gameSlug", "serverName", "serverSlug", "codashopIndex") VALUES('scroll-of-onymyoji', 'S487-Cursa', 's487-cursa', '0');

    ''')


def downgrade() -> None:
    op.execute('DELETE FROM "MTServer" WHERE "gameSlug" = \'scroll-of-onymyoji\'')
